// File generated by importSupportedLocalesFromLocalazy.py, do not edit
// HaohaoChat: 个人构建仅保留 en + zh-rCN，移除其他 37 种语言以减小 APK 体积和资源处理开销

package extension

val locales = setOf(
    "en",
    "zh-rCN",
)
